### ISSUE TITLE
Cellnames missing after running SASC-viz.py

### ISSUE THREAD

**Issue by jmfa** [sciccolella/sasc#1] opened 2021-08-16 15:21 UTC
Hi,

I'm trying out SASC and would like to know whether it is posible to keep the cell names after running the SASC-viz.py script?
I've ran SASC with the `-l` argument together with the cell IDs (using the `-E` option). 
Everything worked correctly and even though the cell IDs are indeed present in the SASC output, they disappear after running SASC-viz.py.

Thanks in advance,
Joao

**Comment by sciccolella** [comment] 2021-09-21 09:16
Hi Joao,
The issue is now fixed with the lates commit. Please use the option `--show-cell-labels` to have the desired effect.

Simone.

**Closed as completed by sciccolella** 2021-09-21 09:16 UTC
